#ifndef MAIN_H
#define MAIN_H

//function declaration
void fileOpen();
void copyrightCheck();
void prtiFunc();
void prtsFunc();
void popsFunc();
void cmpFunc();
bool modFunc();
bool divFunc();
bool mulFunc();
bool subFunc();
bool addFunc();
void decFunc();
void incFunc();
void jmpFunc();
void jmpeqFunc();
void jmpneFunc();
void jmpgeFunc();
void jmpgtFunc();
void jmpltFunc();
void jmpleFunc();
void rdsFunc();
void rdiFunc();
void popiFunc();
void pushksFunc();
void pushkiFunc();
void pushsFunc();
void pushiFunc();
void pushkfFunc();
void popfFunc();
void prtfFunc();
void pushkcFunc();
void popcFunc();
void prtcFunc();
void pushkdFunc();
void popdFunc();
void prtdFunc();
void pushcFunc();
void pushfFunc();
void pushdFunc();
bool rdcFunc();
void rdfFunc();
void rddFunc();
bool popxFunc();
void stkxFunc();
void stxFunc();
void pushaiFunc();
void popaiFunc();

#endif